stages:
  - build

build:
  stage: build
  image: maven:3.8-eclipse-temurin-8
  script:
    - chmod +x install-libs.sh
    - ./install-libs.sh
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - target/*.war
