#!/bin/bash
mkdir -p ~/.m2/repository
mvn install:install-file -Dfile="lib/activation.jar" -DgroupId=local -DartifactId=activation -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/asm-1.4.1.jar" -DgroupId=local -DartifactId=asm -Dversion=1.4.1 -Dpackaging=jar
mvn install:install-file -Dfile="lib/asm-util-1.4.1.jar" -DgroupId=local -DartifactId=asm-util -Dversion=1.4.1 -Dpackaging=jar
mvn install:install-file -Dfile="lib/aspectjrt.jar" -DgroupId=local -DartifactId=aspectjrt -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/cglib-asm-1.0.jar" -DgroupId=local -DartifactId=cglib-asm -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/commons-codec-1.3.jar" -DgroupId=local -DartifactId=commons-codec -Dversion=1.3 -Dpackaging=jar
mvn install:install-file -Dfile="lib/commons-collections.jar" -DgroupId=local -DartifactId=commons-collections -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/commons-dbcp-1.1.jar" -DgroupId=local -DartifactId=commons-dbcp -Dversion=1.1 -Dpackaging=jar
mvn install:install-file -Dfile="lib/commons-httpclient-3.0-rc3.jar" -DgroupId=local -DartifactId=commons-httpclient -Dversion=3.0-rc3 -Dpackaging=jar
mvn install:install-file -Dfile="lib/commons-logging.jar" -DgroupId=local -DartifactId=commons-logging -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/commons-pool-1.1.jar" -DgroupId=local -DartifactId=commons-pool -Dversion=1.1 -Dpackaging=jar
mvn install:install-file -Dfile="lib/dom4j.jar" -DgroupId=local -DartifactId=dom4j -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/dynaop-1.0-beta.jar" -DgroupId=local -DartifactId=dynaop -Dversion=1.0-beta -Dpackaging=jar
mvn install:install-file -Dfile="lib/gabriel.jar" -DgroupId=local -DartifactId=gabriel -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/graph-snipsnap.jar" -DgroupId=local -DartifactId=graph-snipsnap -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/groovy-1.0-beta-6.jar" -DgroupId=local -DartifactId=groovy -Dversion=1.0-beta-6 -Dpackaging=jar
mvn install:install-file -Dfile="lib/j2h.jar" -DgroupId=local -DartifactId=j2h -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/javax.servlet.jar" -DgroupId=local -DartifactId=servlet-api -Dversion=2.3 -Dpackaging=jar
mvn install:install-file -Dfile="lib/jdbcstorage-1.0-alpha-1.jar" -DgroupId=local -DartifactId=jdbcstorage -Dversion=1.0-alpha-1 -Dpackaging=jar
mvn install:install-file -Dfile="lib/jdic.jar" -DgroupId=local -DartifactId=jdic -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/jdom-1.0.jar" -DgroupId=local -DartifactId=jdom -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/jena.jar" -DgroupId=local -DartifactId=jena -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/jmdns.jar" -DgroupId=local -DartifactId=jmdns -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/jmock-1.0.0.jar" -DgroupId=local -DartifactId=jmock -Dversion=1.0.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/junit-3.8.1.jar" -DgroupId=local -DartifactId=junit -Dversion=3.8.1 -Dpackaging=jar
mvn install:install-file -Dfile="lib/junit.jar" -DgroupId=local -DartifactId=junit -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/junitperf.jar" -DgroupId=local -DartifactId=junitperf -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/jython.jar" -DgroupId=local -DartifactId=jython -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/lucene-1.4.1.jar" -DgroupId=local -DartifactId=lucene -Dversion=1.4.1 -Dpackaging=jar
mvn install:install-file -Dfile="lib/mail.jar" -DgroupId=local -DartifactId=mail -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/mckoidb.jar" -DgroupId=local -DartifactId=mckoidb -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/mysql-connector.jar" -DgroupId=local -DartifactId=mysql-connector -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/nanocontainer-1.0.jar" -DgroupId=local -DartifactId=nanocontainer -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/nanocontainer-dynaop-1.0-beta-1-SNAPSHOT.jar" -DgroupId=local -DartifactId=nanocontainer-dynaop -Dversion=1.0-beta-1-SNAPSHOT -Dpackaging=jar
mvn install:install-file -Dfile="lib/org.apache.jasper.jar" -DgroupId=local -DartifactId=org.apache.jasper -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/org.mortbay.jetty.jar" -DgroupId=local -DartifactId=org.mortbay.jetty -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/picocontainer-1.0.jar" -DgroupId=local -DartifactId=picocontainer -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/postgres-jdbc.jar" -DgroupId=local -DartifactId=postgres-jdbc -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/radeox.jar" -DgroupId=local -DartifactId=radeox -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/rome-0.5.jar" -DgroupId=local -DartifactId=rome -Dversion=0.5 -Dpackaging=jar
mvn install:install-file -Dfile="lib/rss-ng-1.0-alpha-1.jar" -DgroupId=local -DartifactId=rss-ng -Dversion=1.0-alpha-1 -Dpackaging=jar
mvn install:install-file -Dfile="lib/search-ng-1.0-alpha-1.jar" -DgroupId=local -DartifactId=search-ng -Dversion=1.0-alpha-1 -Dpackaging=jar
mvn install:install-file -Dfile="lib/smack.jar" -DgroupId=local -DartifactId=smack -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/spring-beans.jar" -DgroupId=local -DartifactId=spring-beans -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/spring-core.jar" -DgroupId=local -DartifactId=spring-core -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="lib/xmlrpc-2.0-beta.jar" -DgroupId=local -DartifactId=xmlrpc -Dversion=2.0-beta -Dpackaging=jar
mvn install:install-file -Dfile="src/apps/default/WEB-INF/lib/jstl.jar" -DgroupId=local -DartifactId=jstl -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile="src/apps/default/WEB-INF/lib/standard.jar" -DgroupId=local -DartifactId=standard -Dversion=1.0 -Dpackaging=jar
