<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.snipsnap</groupId>
  <artifactId>snipsnap</artifactId>
  <packaging>war</packaging>
  <version>1.0-SNAPSHOT</version>
  <name>SnipSnap</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <repositories>
    <repository>
        <id>maven-central</id>
        <url>https://repo.maven.apache.org/maven2</url>
    </repository>
  </repositories>

  <dependencies>
    <!-- Standard Deps -->
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>servlet-api</artifactId>
      <version>2.3</version>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>jstl</artifactId>
      <version>1.1.2</version>
    </dependency>
    <dependency>
      <groupId>taglibs</groupId>
      <artifactId>standard</artifactId>
      <version>1.1.2</version>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
    </dependency>
    <dependency>
      <groupId>org.apache.ant</groupId>
      <artifactId>ant</artifactId>
      <version>1.10.12</version>
    </dependency>
    <dependency>
      <groupId>commons-codec</groupId>
      <artifactId>commons-codec</artifactId>
      <version>1.3</version>
    </dependency>
    <dependency>
      <groupId>commons-collections</groupId>
      <artifactId>commons-collections</artifactId>
      <version>3.1</version>
    </dependency>
    <dependency>
      <groupId>commons-dbcp</groupId>
      <artifactId>commons-dbcp</artifactId>
      <version>1.1</version>
      <exclusions>
        <exclusion>
            <groupId>javax.sql</groupId>
            <artifactId>jdbc-stdext</artifactId>
        </exclusion>
        <exclusion>
            <groupId>xml-apis</groupId>
            <artifactId>xml-apis</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>commons-httpclient</groupId>
      <artifactId>commons-httpclient</artifactId>
      <version>3.0-rc3</version>
    </dependency>
    <dependency>
      <groupId>commons-logging</groupId>
      <artifactId>commons-logging</artifactId>
      <version>1.0.4</version>
    </dependency>
    <dependency>
      <groupId>commons-pool</groupId>
      <artifactId>commons-pool</artifactId>
      <version>1.1</version>
      <exclusions>
         <exclusion>
            <groupId>javax.sql</groupId>
            <artifactId>jdbc-stdext</artifactId>
         </exclusion>
         <exclusion>
            <groupId>xml-apis</groupId>
            <artifactId>xml-apis</artifactId>
         </exclusion>
      </exclusions>
    </dependency>
    <dependency>
        <groupId>dom4j</groupId>
        <artifactId>dom4j</artifactId>
        <version>1.6.1</version>
    </dependency>
    <dependency>
        <groupId>jdom</groupId>
        <artifactId>jdom</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>jmock</groupId>
        <artifactId>jmock</artifactId>
        <version>1.0.0</version>
    </dependency>
    <dependency>
        <groupId>lucene</groupId>
        <artifactId>lucene</artifactId>
        <version>1.4.1</version>
    </dependency>
    <dependency>
        <groupId>javax.mail</groupId>
        <artifactId>mail</artifactId>
        <version>1.4</version>
    </dependency>
    <dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
        <version>3.1.14</version>
    </dependency>
    <dependency>
        <groupId>postgresql</groupId>
        <artifactId>postgresql</artifactId>
        <version>9.1-901-1.jdbc4</version>
    </dependency>
    <dependency>
        <groupId>asm</groupId>
        <artifactId>asm</artifactId>
        <version>1.4.1</version>
    </dependency>
    <dependency>
        <groupId>asm</groupId>
        <artifactId>asm-util</artifactId>
        <version>1.4.1</version>
    </dependency>
    <dependency>
        <groupId>cglib</groupId>
        <artifactId>cglib-asm</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>org.aspectj</groupId>
        <artifactId>aspectjrt</artifactId>
        <version>1.2.0-snipsnap</version>
    </dependency>
     <dependency>
        <groupId>javax.activation</groupId>
        <artifactId>activation</artifactId>
        <version>1.1</version>
    </dependency>

    <!-- Local/Custom Deps -->
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>dynaop</artifactId>
        <version>1.0-beta</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>gabriel</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>graph-snipsnap</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>j2h</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>jdbcstorage</artifactId>
        <version>1.0-alpha-1</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>jdic</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>jena</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>jmdns</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>jython</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>com.mckoi</groupId>
        <artifactId>mckoidb</artifactId>
        <version>1.0.3</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>nanocontainer-dynaop</artifactId>
        <version>1.0-beta-1-SNAPSHOT</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>jasper</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>jetty</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>radeox</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>rss-ng</artifactId>
        <version>1.0-alpha-1</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>search-ng</artifactId>
        <version>1.0-alpha-1</version>
    </dependency>
    <dependency>
        <groupId>org.snipsnap.local</groupId>
        <artifactId>smack</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-beans</artifactId>
        <version>1.2.9-snipsnap</version>
    </dependency>
    <dependency>
        <groupId>org.springframework</groupId>
        <artifactId>spring-core</artifactId>
        <version>1.2.9-snipsnap</version>
    </dependency>
    <dependency>
        <groupId>groovy</groupId>
        <artifactId>groovy</artifactId>
        <version>1.0-beta-6</version>
    </dependency>
    <dependency>
        <groupId>nanocontainer</groupId>
        <artifactId>nanocontainer</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>picocontainer</groupId>
        <artifactId>picocontainer</artifactId>
        <version>1.0</version>
    </dependency>
    <dependency>
        <groupId>xmlrpc</groupId>
        <artifactId>xmlrpc</artifactId>
        <version>2.0-beta</version>
    </dependency>
    <dependency>
        <groupId>rome</groupId>
        <artifactId>rome</artifactId>
        <version>0.5</version>
    </dependency>
  </dependencies>
  <build>
    <sourceDirectory>src</sourceDirectory>
    <resources>
        <resource>
            <directory>src</directory>
            <excludes>
                <exclude>**/*.java</exclude>
            </excludes>
        </resource>
        <resource>
            <directory>conf</directory>
            <targetPath>conf</targetPath>
        </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <version>3.3.2</version>
        <configuration>
          <warSourceDirectory>src/apps/default</warSourceDirectory>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
            <source>1.8</source>
            <target>1.8</target>
            <excludes>
                <exclude>org/snipsnap/test/**</exclude>
            </excludes>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-antrun-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
            <execution>
                <id>generate-sources</id>
                <phase>generate-sources</phase>
                <configuration>
                    <target>
                        <mkdir dir="${project.build.directory}/generator-classes"/>
                        <javac srcdir="src" destdir="${project.build.directory}/generator-classes" includes="org/snipsnap/util/PropertyConstantBuilder.java" classpathref="maven.compile.classpath"/>

                        <taskdef name="constants" classname="org.snipsnap.util.PropertyConstantBuilder" classpath="${project.build.directory}/generator-classes:${maven.compile.classpath}"/>

                        <mkdir dir="${project.build.directory}/ant"/>
                        <constants properties="src/org/snipsnap/config/defaults.conf" file="${project.build.directory}/ant/config.stub" prefix="app."/>
                        <constants properties="src/org/snipsnap/config/globals.conf" file="${project.build.directory}/ant/globals.stub" prefix="app."/>

                        <loadfile property="config-stub" srcfile="${project.build.directory}/ant/config.stub"/>
                        <loadfile property="globals-stub" srcfile="${project.build.directory}/ant/globals.stub"/>

                        <copy file="src/org/snipsnap/config/Configuration.java.tmpl" tofile="src/snipsnap/api/config/Configuration.java" overwrite="true">
                            <filterset>
                                <filter token="DEFAULTS" value="${config-stub}"/>
                            </filterset>
                        </copy>
                        <copy file="src/org/snipsnap/config/Globals.java.tmpl" tofile="src/org/snipsnap/config/Globals.java" overwrite="true">
                            <filterset>
                                <filter token="DEFAULTS" value="${globals-stub}"/>
                            </filterset>
                        </copy>
                    </target>
                </configuration>
                <goals>
                    <goal>run</goal>
                </goals>
            </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
